### ISSUE TITLE
problems on  LSTM-based probabilities 

### ISSUE THREAD

**Issue by fivehills** [langcomp/lm_1b#1]
When implementing according to the instruction, I have met some problems in "Create LSTM-based probabilities 2. A GoogleLanguageModel is created. This relies on code and files from Tal Linzen's rnn_agreement codebase. Thedirectory where these files are stored should be hardcoded into filenames.py ." 
The problem looks as follows: 

>>> rnn_file = 'output.csv'
>>> rnn_corpus.create(tokenized_line_file, rnn_file)
Recovering graph.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "rnn_corpus.py", line 19, in create
    glm = GoogleLanguageModel()
  File "google_lm.py", line 32, in __init__
    self.load_model(pbtxt, ckpt) 
  File "google_lm.py", line 49, in load_model
    s = f.read()
  File "/home/kun/.local/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 120, in read
    self._preread_check()
  File "/home/kun/.local/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 80, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/home/kun/.local/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /home/kun/Software/entropy/lm_1b-master/raw_data/lm_1b/graph-2016-09-10.pbtxt; No such file or directory

Then I checked the script "google_lm.py",  finding that some files are missing:

class GoogleLanguageModel(object):

    pbtxt = 'graph-2016-09-10.pbtxt'
    ckpt = 'ckpt-*'
    vocab_file = 'vocab-2016-09-10.txt'

How to solve the problem? 
Many thanks!

**Comment by angoodkind** [comment]
Please see the second instruction on the README. Thanks
